#!/bin/bash5.0.18
echo "Opelopejesu Tolulope Owolabi";
Opelopejesu Tolulope Owolabi
echo "opelopejesu97@gmail.com";
opelopejesu97@gmail.com
echo "bash";
bash
echo "genomics";
genomics
echo "@Opelopejesu";
@Opelopejesu
$
